websites = {
    # Search Engines
    "google": "google.com",
    "bing": "bing.com",
    "duckduckgo": "duckduckgo.com",
    "yahoo": "yahoo.com",
    "baidu": "baidu.com",
    "yandex": "yandex.ru",
    "ask": "ask.com",
    "aol": "aol.com",

    # Social Media
    "facebook": "facebook.com",
    "instagram": "instagram.com",
    "x": "x.com",
    "threads": "threads.net",
    "snapchat": "snapchat.com",
    "tiktok": "tiktok.com",
    "linkedin": "linkedin.com",
    "reddit": "reddit.com",
    "quora": "quora.com",
    "pinterest": "pinterest.com",
    "tumblr": "tumblr.com",
    "wechat": "wechat.com",

    # Video & Streaming
    "youtube": "youtube.com",
    "twitch": "twitch.tv",
    "netflix": "netflix.com",
    "primevideo": "primevideo.com",
    "hotstar": "hotstar.com",
    "hulu": "hulu.com",
    "disneyplus": "disneyplus.com",
    "zee5": "zee5.com",
    "sonyLiv": "sonyliv.com",
    "mxplayer": "mxplayer.in",

    # Productivity
    "notion": "notion.so",
    "canva": "canva.com",
    "figma": "figma.com",
    "monday": "monday.com",
    "slack": "slack.com",
    "trello": "trello.com",
    "zoom": "zoom.us",
    "skype": "skype.com",
    "calendly": "calendly.com",
    "airtable": "airtable.com",
    "miro": "miro.com",
    "onedrive": "onedrive.live.com",
    "dropbox": "dropbox.com",
    "google_drive": "drive.google.com",

    # Development & Tech
    "github": "github.com",
    "gitlab": "gitlab.com",
    "stackoverflow": "stackoverflow.com",
    "w3schools": "w3schools.com",
    "codepen": "codepen.io",
    "replit": "replit.com",
    "npm": "npmjs.com",
    "vercel": "vercel.com",
    "netlify": "netlify.app",
    "hackerrank": "hackerrank.com",
    "leetcode": "leetcode.com",
    "geeksforgeeks": "geeksforgeeks.org",

    # Design & Media
    "adobe": "adobe.com",
    "unsplash": "unsplash.com",
    "pexels": "pexels.com",
    "pixabay": "pixabay.com",
    "dribbble": "dribbble.com",
    "behance": "behance.net",
    "oneshot": "oneshot.ai",
    "fotor": "fotor.com",
    "removebg": "remove.bg",

    # Shopping
    "amazon": "amazon.com",
    "flipkart": "flipkart.com",
    "ebay": "ebay.com",
    "aliexpress": "aliexpress.com",
    "temu": "temu.com",
    "shopify": "shopify.com",
    "ajio": "ajio.com",
    "myntra": "myntra.com",
    "meesho": "meesho.com",
    "etsy": "etsy.com",

    # Education
    "coursera": "coursera.org",
    "udemy": "udemy.com",
    "edx": "edx.org",
    "khanacademy": "khanacademy.org",
    "brilliant": "brilliant.org",
    "unacademy": "unacademy.com",
    "byjus": "byjus.com",
    "nptel": "nptel.ac.in",

    # AI & Tools
    "chatgpt": "chat.openai.com",
    "bard": "bard.google.com",
    "perplexity": "perplexity.ai",
    "poe": "poe.com",
    "gamma": "gamma.app",
    "phind": "phind.com",
    "midjourney": "midjourney.com",
    "d-id": "d-id.com",
    "runway": "runwayml.com",

    # News
    "bbc": "bbc.com",
    "cnn": "cnn.com",
    "nyt": "nytimes.com",
    "reuters": "reuters.com",
    "bloomberg": "bloomberg.com",
    "theguardian": "theguardian.com",
    "hindu": "thehindu.com",
    "toi": "timesofindia.indiatimes.com",
    "hindustantimes": "hindustantimes.com",
    "indianexpress": "indianexpress.com"
}
